GET https://webdev-18s1-mmgoodnow.herokuapp.com/api/course

###

POST https://webdev-18s1-mmgoodnow.herokuapp.com/api/course
Content-Type: application/json

{
    "title": "MATH2345",
    "owner": {
        "id":92
    }
}

###

PUT https://webdev-18s1-mmgoodnow.herokuapp.com/api/course
Content-Type: application/json

{
    "id": 42,
    "title": "New Course",
    "owner": {
        "id": 92
    }
}

###

POST http://sage.local:8080/api/lesson/622/assignment
Content-Type: application/json

{
    "title": "Assignment 2",
    "points": 20,
    "description": "This is the other one"
}

###

DELETE http://sage.local:8080/api/widget/12

###

POST http://sage.local:8080/api/lesson/622/exam
Content-Type: application/json

{
    "title": "Exam 2",
    "questions": []
}

###

GET http://sage.local:8080/api/lesson/622/widget

###
